# Generated by Django 4.1 on 2022-09-16 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0018_alter_modelcursos_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Forum do Curso', max_length=100, verbose_name='titulo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.modelcursos', verbose_name='forum')),
            ],
            options={
                'verbose_name': 'Forum do curso',
            },
        ),
        migrations.CreateModel(
            name='Topicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titulo')),
                ('assunto', models.TextField(verbose_name='Assunto')),
                ('notificacoes', models.BooleanField(blank=True, default=False, verbose_name='Deseja receber notificações sobre este Topico?')),
                ('num_respostas', models.IntegerField(blank=True, default=0, verbose_name='Numero de respostas')),
                ('visualizacoes', models.IntegerField(blank=True, default=0, verbose_name='Visualisações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.forum', verbose_name='topicos')),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField(verbose_name='Resposta')),
                ('like', models.IntegerField(blank=True, default=0, verbose_name='Numero de Likes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forum.topicos', verbose_name='respostas')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['atualizado_em'],
            },
        ),
    ]
