# Generated by Django 4.1 on 2022-09-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='topicos',
            old_name='title',
            new_name='titulo',
        ),
    ]
