# Generated by Django 4.1 on 2022-09-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_alter_modelcursos_user'),
        ('forum', '0003_alter_respostas_autor_alter_topicos_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cursos.modelcursos', verbose_name='forum'),
        ),
    ]
