# Generated by Django 4.1 on 2022-09-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0018_alter_modelcursos_user'),
        ('forum', '0004_alter_forum_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respostas',
            options={'ordering': ['criado_em'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forum', to='cursos.modelcursos'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='forum.topicos'),
        ),
        migrations.AlterField(
            model_name='topicos',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autor_t', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topicos',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicos', to='forum.forum'),
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_r', to='forum.respostas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
            },
        ),
    ]
