# Generated by Django 4.1 on 2022-09-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0005_alter_respostas_options_alter_forum_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='topico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='forum.topicos'),
        ),
    ]
