# Generated by Django 4.0.5 on 2022-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('image', models.ImageField(upload_to='cursos/imagens', verbose_name='imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
            ],
        ),
    ]
