# Generated by Django 4.1 on 2022-08-16 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="modelcursos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Titulo do curso"),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="descrição breve"),
                ),
                (
                    "sobre_curso",
                    models.TextField(blank=True, verbose_name="sobre o curso"),
                ),
                ("slug", models.SlugField(verbose_name="Atalho")),
                (
                    "data_inicio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de inicio"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cursos/imagens",
                        verbose_name="imagem",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em: "),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="atualizado em: "),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
                "verbose_name_plural": "Cursos",
            },
        ),
    ]
