# Generated by Django 4.0.6 on 2022-08-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/imagens', verbose_name='imagem'),
        ),
    ]
