# Generated by Django 4.0.5 on 2022-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_cursos_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursosmanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='cursos',
            name='sobre_curso',
            field=models.TextField(blank=True, verbose_name='sobre o curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição breve'),
        ),
    ]
