# Generated by Django 4.0.5 on 2022-07-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_cursosmanage_alter_cursos_options_cursos_sobre_curso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cursosmanage',
        ),
    ]
