# Generated by Django 4.0.6 on 2022-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_delete_cursosmanage'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelcursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Titulo do curso')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição breve')),
                ('sobre_curso', models.TextField(blank=True, verbose_name='sobre o curso')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cursos/imagens', verbose_name='imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.DeleteModel(
            name='cursos',
        ),
    ]
