# Generated by Django 4.1 on 2022-09-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_categoria_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcursos',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.categoria_curso'),
            preserve_default=False,
        ),
    ]
