# Generated by Django 4.1 on 2022-09-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_modulo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do modulo')),
                ('video', models.TextField(blank=True, verbose_name='Video')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aulas', to='cursos.modulo_curso')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
    ]
