# Generated by Django 4.1 on 2022-09-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_aulas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aulas',
            new_name='aulas_curso',
        ),
        migrations.AlterModelOptions(
            name='aulas_curso',
            options={'verbose_name': 'Aula curso', 'verbose_name_plural': 'Aulas cursos'},
        ),
    ]
