# Generated by Django 4.1 on 2022-09-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_rename_aulas_aulas_curso_alter_aulas_curso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas_curso',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo da Aula'),
        ),
        migrations.AlterField(
            model_name='aulas_curso',
            name='video',
            field=models.TextField(verbose_name='Video'),
        ),
    ]
