# Generated by Django 4.1 on 2022-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_alter_aulas_curso_titulo_alter_aulas_curso_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas_curso',
            name='sobre_aula',
            field=models.TextField(blank=True, null=True, verbose_name='sobre a aula'),
        ),
        migrations.AlterField(
            model_name='aulas_curso',
            name='video',
            field=models.CharField(max_length=100, verbose_name='link do Video'),
        ),
    ]
