# Generated by Django 4.1 on 2022-09-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_aulas_curso_numero_aula'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo_curso',
            name='numero_modulo',
            field=models.IntegerField(blank=True, default=0, verbose_name='numero aula'),
        ),
    ]
