# Generated by Django 4.1 on 2022-09-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_matricula_notificacoes_avisos_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avisos_curso',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
    ]
