# Generated by Django 4.1 on 2022-09-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_alter_avisos_curso_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisos_curso',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='notificacoes',
            field=models.BooleanField(blank=True, default=True, verbose_name='deseja receber notificações do curso'),
        ),
        migrations.CreateModel(
            name='materiais_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do material')),
                ('material', models.FileField(upload_to='cursos/materiais', verbose_name='Material')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiais', to='cursos.modelcursos')),
            ],
            options={
                'verbose_name': 'Aula curso',
            },
        ),
    ]
