# Generated by Django 4.1 on 2022-09-16 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0017_alter_materiais_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcursos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
