# Generated by Django 4.1 on 2022-09-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0018_alter_modelcursos_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria_curso",
            name="descricao",
            field=models.TextField(blank=True, verbose_name="descrição breve"),
        ),
    ]
