# Generated by Django 4.1 on 2022-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_alter_modelcursos_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcursos',
            name='descricao',
            field=models.TextField(blank=True, max_length=150, verbose_name='descrição breve'),
        ),
        migrations.AlterField(
            model_name='modelcursos',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Titulo do curso'),
        ),
    ]
