# Generated by Django 4.1 on 2022-09-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_alter_modelcursos_descricao_alter_modelcursos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelcursos',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, verbose_name='descrição breve'),
        ),
        migrations.AlterField(
            model_name='modelcursos',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Titulo do curso'),
        ),
    ]
