# Generated by Django 4.0.6 on 2022-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redefinir_senha',
            name='expira_em',
            field=models.TimeField(null=True, verbose_name='tempo para expirar'),
        ),
        migrations.AddField(
            model_name='redefinir_senha',
            name='horario',
            field=models.TimeField(auto_now=True, verbose_name='horario de criação'),
        ),
    ]
