# Generated by Django 4.0.6 on 2022-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_imageperfil_user_nome_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
    ]
