# Generated by Django 4.0.6 on 2022-08-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_modelprofessor_qualificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaluno',
            name='imageperfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/imagens', verbose_name='imagem perfil'),
        ),
    ]
