# Generated by Django 4.0.6 on 2022-08-19 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='redefinir_senha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=100, unique=True, verbose_name='key')),
                ('criado_em', models.DateField(auto_now=True, verbose_name='Data criação')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Senha foi redefinida:')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resets', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
